#pragma once

#include <memory>
#include <unordered_map>
#include <string>

#include "glm.hpp"
#include "ft2build.h"
#include FT_FREETYPE_H

#include "Texture.h"
#include "Material.h"

class Camera2D;


struct EngineContext;

/**
 * @brief Horizontal alignment options used when generating text geometry.
 *
 * @details
 * This enum controls how each line of text is positioned horizontally
 * when Font::GenerateTextMesh() builds a mesh.
 *
 * The current implementation applies alignment per line:
 * - Left keeps the line start at the local origin.
 * - Center offsets the line by half of its width.
 * - Right offsets the line by the full line width. :contentReference[oaicite:1]{index=1}
 */
enum class TextAlignH
{
    Left,
    Center,
    Right
};

/**
 * @brief Vertical alignment options used when generating text geometry.
 *
 * @details
 * This enum controls the vertical starting position of the generated text block
 * when Font::GenerateTextMesh() builds multiline text geometry.
 *
 * The current implementation adjusts the initial y cursor based on total line count:
 * - Top starts from the top-aligned baseline region.
 * - Middle centers the text block vertically.
 * - Bottom places the block so its bottom line is aligned last. :contentReference[oaicite:2]{index=2}
 */
enum class TextAlignV
{
    Top,
    Middle,
    Bottom
};

/**
 * @brief Stores baked glyph metrics and UV information inside the font atlas.
 *
 * @details
 * Each Glyph entry describes one Unicode codepoint that has been baked into the atlas texture.
 * The stored data is later used to measure text and generate quad geometry.
 *
 * The current implementation stores:
 * - pixel size of the bitmap
 * - bearing from the baseline/origin
 * - advance value from FreeType
 * - normalized atlas UV coordinates for the glyph rectangle :contentReference[oaicite:3]{index=3}
 */
struct Glyph
{
    /**
     * @brief Bitmap size of the glyph in pixels.
     */
    glm::ivec2 size;

    /**
     * @brief Glyph bearing relative to the text origin and baseline.
     */
    glm::ivec2 bearing;

    /**
     * @brief Horizontal advance in 1/64 pixel units from FreeType.
     *
     * @details
     * The current implementation converts this using (advance >> 6)
     * when measuring text width or advancing the text cursor. :contentReference[oaicite:4]{index=4}
     */
    uint32_t advance;

    /**
     * @brief Top-left UV coordinate of the baked glyph in the atlas.
     */
    glm::vec2 uvTopLeft;

    /**
     * @brief Bottom-right UV coordinate of the baked glyph in the atlas.
     */
    glm::vec2 uvBottomRight;
};

/**
 * @brief FreeType-backed font resource that manages glyph baking, atlas storage, and text mesh generation.
 *
 * @details
 * Font is responsible for:
 * - loading a TTF face through FreeType
 * - creating and maintaining a single glyph atlas texture
 * - lazily baking glyphs on demand
 * - providing a text rendering material bound to the atlas
 * - measuring UTF-8 text
 * - generating a Mesh for aligned text rendering
 *
 * The current implementation uses a dynamically growing single atlas.
 * Glyphs are not pre-generated for all characters. Instead, characters are baked
 * as needed through TryBakeGlyph(), and the atlas is expanded when there is not enough space. :contentReference[oaicite:5]{index=5}
 *
 * The material created by this class uses the internal engine text shader
 * registered by RenderManager during initialization, and binds the atlas texture
 * to the uniform "u_FontTexture".
 *
 * @note
 * This class owns the FreeType library handle and font face and releases them in the destructor.
 *
 * @note
 * atlasVersion is incremented whenever the atlas is rebuilt during expansion.
 * External systems such as TextObject can use this value to detect when text meshes
 * need to be regenerated.
 */
class Font
{
public:
    /**
     * @brief Constructs a font from a TrueType file and prepares its atlas/material.
     *
     * @details
     * The constructor loads the font face, sets the pixel size, creates an initial
     * empty atlas texture, and prepares a material using the engine's internal text shader.
     *
     * @param engineContext Render manager used to obtain the internal text shader and build the material.
     * @param ttfPath Path to the .ttf font file.
     * @param fontSize Pixel size requested from FreeType.
     */
    Font(RenderManager& renderManager, const std::string& ttfPath, uint32_t fontSize);

    /**
     * @brief Releases FreeType resources owned by this font.
     *
     * @details
     * The current implementation calls FT_Done_Face() and FT_Done_FreeType(). :contentReference[oaicite:9]{index=9}
     */
    ~Font();

    /**
     * @brief Returns the material used to render text generated by this font.
     *
     * @details
     * The material is created during atlas initialization and is configured to use
     * the internal text shader and the current atlas texture.
     *
     * @return Shared pointer to the font material.
     */
    [[nodiscard]] std::shared_ptr<Material> GetMaterial() const { return material; }

    /**
     * @brief Measures the size of a UTF-8 text string.
     *
     * @details
     * The current implementation decodes the input into Unicode codepoints,
     * sums glyph advances for each line, tracks the maximum line width,
     * and computes total height as fontSize multiplied by the number of lines. :contentReference[oaicite:11]{index=11}
     *
     * Newline characters split the text into multiple lines.
     *
     * @param text UTF-8 encoded text.
     * @return A vec2 containing the measured width and height in local text space.
     *
     * @note
     * Width is based on advance values, not actual bitmap bounds.
     */
    [[nodiscard]] glm::vec2 GetTextSize(const std::string& text) const;

    /**
     * @brief Generates a mesh containing textured quads for the given UTF-8 text.
     *
     * @details
     * The function:
     * - splits text into lines
     * - pre-bakes glyphs required for width calculation
     * - computes per-line width
     * - applies horizontal and vertical alignment offsets
     * - generates one quad per glyph with matching atlas UVs
     * - returns the resulting Mesh built from vertices and indices :contentReference[oaicite:12]{index=12}
     *
     * Missing glyphs are baked on demand through TryBakeGlyph().
     *
     * @param text UTF-8 encoded text.
     * @param alignH Horizontal alignment for each line.
     * @param alignV Vertical alignment for the text block.
     * @return Shared pointer to a newly generated text mesh.
     */
    [[nodiscard]] std::shared_ptr<Mesh> GenerateTextMesh(const std::string& text, TextAlignH alignH = TextAlignH::Left, TextAlignV alignV = TextAlignV::Top);

    /**
     * @brief Returns the current atlas version number.
     *
     * @details
     * The version increases when the atlas is expanded and glyph UVs are regenerated.
     * External text objects can use this value to detect stale mesh data and rebuild it.
     *
     * @return Current atlas version.
     */
    int GetTextAtlasVersion() { return atlasVersion; }

private:
    /**
     * @brief Initializes FreeType and loads the requested font face.
     *
     * @details
     * The current implementation:
     * - calls FT_Init_FreeType()
     * - calls FT_New_Face()
     * - sets the pixel size through FT_Set_Pixel_Sizes() :contentReference[oaicite:14]{index=14}
     *
     * @param path Path to the .ttf file.
     * @param fontSize Requested pixel size.
     *
     * @note
     * Throws std::runtime_error if FreeType initialization or face loading fails. :contentReference[oaicite:15]{index=15}
     */
    void LoadFont(const std::string& path, uint32_t fontSize);

    /**
     * @brief Creates the initial empty atlas texture and text material.
     *
     * @details
     * The current implementation starts with a 128x128 single-channel texture,
     * sets OpenGL unpack alignment to 1 during upload, retrieves the internal text shader
     * from RenderManager, creates a Material, binds the atlas as "u_FontTexture",
     * and initializes the default text color uniform.
     *
     * @param renderManager Render manager used to resolve the internal text shader.
     */
    void BakeAtlas(RenderManager& renderManager);

    /**
     * @brief Returns the baked glyph data for a codepoint.
     *
     * @details
     * If the exact codepoint is not found, the current implementation falls back to
     * the glyph for '?' if available. If that is also missing, a static empty Glyph is returned. :contentReference[oaicite:17]{index=17}
     *
     * @param c Unicode codepoint.
     * @return Reference to the matching or fallback glyph data.
     */
    [[nodiscard]] const Glyph& GetGlyph(char32_t c) const;

    /**
     * @brief Ensures that the specified codepoint exists in the atlas.
     *
     * @details
     * If the glyph is already baked, the function returns true immediately.
     * Otherwise, it renders the glyph using FreeType, packs it into the atlas,
     * stores size/bearing/advance/UV metadata, and updates atlas packing cursors. :contentReference[oaicite:18]{index=18}
     *
     * If the current atlas does not have enough room, ExpandAtlas() is called and the bake is retried.
     *
     * @param c Unicode codepoint to bake.
     * @return True if the glyph is available after the call, false if baking failed.
     *
     * @note
     * Glyphs without a bitmap may still be stored if they have a valid advance.
     */
    [[nodiscard]] bool TryBakeGlyph(char32_t c);

    /**
     * @brief Expands the atlas texture and rebuilds all baked glyph entries.
     *
     * @details
     * The current implementation doubles both atlas width and height,
     * creates a new texture, rebinds it to the material, clears the current packing state,
     * rebakes all previously known glyphs, and increments atlasVersion. :contentReference[oaicite:19]{index=19}
     *
     * @note
     * Because all glyph UVs may change during expansion, any previously generated text mesh
     * that relies on old UV coordinates should be regenerated.
     */
    void ExpandAtlas();

    /**
     * @brief FreeType library handle.
     */
    FT_Library ft;

    /**
     * @brief FreeType face loaded from the font file.
     */
    FT_Face face;

    /**
     * @brief Requested pixel size used for glyph layout and line spacing.
     */
    uint32_t fontSize;

    /**
     * @brief Map of baked Unicode codepoints to glyph metadata.
     */
    std::unordered_map<char32_t, Glyph> glyphs;

    /**
     * @brief Single atlas texture that stores all baked glyph bitmaps.
     */
    std::shared_ptr<Texture> atlasTexture;

    /**
     * @brief Material used to render text geometry generated by this font.
     */
    std::shared_ptr<Material> material;

    /**
     * @brief Current x cursor used by atlas packing.
     */
    int nextX = 0;

    /**
     * @brief Current y cursor used by atlas packing.
     */
    int nextY = 0;

    /**
     * @brief Maximum row height of the currently packed atlas row.
     */
    int maxRowHeight = 0;

    /**
     * @brief Version value that increases when the atlas is rebuilt.
     */
    int atlasVersion = 0;
};