#pragma once
#include "GameObject.h"
#include "Mesh.h"
#include "Material.h"
#include <unordered_map>
#include <vector>

class SpriteSheet;

/**
 * @brief Key structure used for grouping GameObjects into instanced rendering batches.
 *
 * @details
 * InstanceBatchKey represents a unique combination of rendering-relevant resources
 * that must match in order for multiple GameObjects to be rendered together using
 * instanced rendering.
 *
 * The key consists of:
 * - Mesh pointer (geometry)
 * - Material pointer (shader + texture state)
 * - SpriteSheet pointer (optional sprite animation source)
 *
 * Two GameObjects can only be placed in the same instanced batch if all three
 * pointers are identical.
 *
 * This structure is designed to be used as a key in associative containers
 * such as std::unordered_map and std::map.
 */
struct InstanceBatchKey
{
    Mesh* mesh;
    Material* material;
    SpriteSheet* spriteSheet;

    /**
     * @brief Compares two InstanceBatchKey objects for equality.
     *
     * @details
     * Returns true only if mesh, material, and spriteSheet pointers
     * are exactly the same between the two keys.
     *
     * This operator is primarily used by hash-based containers
     * such as std::unordered_map.
     *
     * @param other The key to compare against.
     * @return true if all pointer members match exactly.
     */
    bool operator==(const InstanceBatchKey& other) const
    {
        return mesh == other.mesh && material == other.material && spriteSheet == other.spriteSheet;
    }

    /**
     * @brief Provides a strict weak ordering for InstanceBatchKey.
     *
     * @details
     * This operator enables InstanceBatchKey to be used in ordered containers
     * such as std::map or std::set.
     *
     * The comparison order is:
     * 1. Mesh pointer
     * 2. Material pointer
     * 3. SpriteSheet pointer
     *
     * @param other The key to compare against.
     * @return true if this key is considered less than the other key.
     */
    bool operator<(const InstanceBatchKey& other) const
    {
        if (mesh != other.mesh) return mesh < other.mesh;
        if (material != other.material) return material < other.material;
        return spriteSheet < other.spriteSheet;
    }
};

namespace std
{
    /**
     * @brief Hash specialization for InstanceBatchKey.
     *
     * @details
     * This specialization enables InstanceBatchKey to be used as a key
     * in std::unordered_map.
     *
     * The hash value is generated by combining the hashes of the
     * mesh, material, and spriteSheet pointers using bitwise operations.
     */
    template<>
    struct hash<InstanceBatchKey>
    {
        /**
         * @brief Computes a hash value for an InstanceBatchKey.
         *
         * @param key The InstanceBatchKey to hash.
         * @return A combined hash value representing the key.
         */
        std::size_t operator()(const InstanceBatchKey& key) const noexcept
        {
            std::size_t h1 = std::hash<Mesh*>()(key.mesh);
            std::size_t h2 = std::hash<Material*>()(key.material);
            std::size_t h3 = std::hash<SpriteSheet*>()(key.spriteSheet);
            return h1 ^ (h2 << 1) ^ (h3 << 2);
        }
    };
}

/**
 * @brief Map structure used for organizing instanced rendering batches per render layer.
 *
 * @details
 * The outer map key (int) typically represents a render layer or render order.
 *
 * Each layer contains an unordered_map where:
 * - The key is InstanceBatchKey (shared render state)
 * - The value is a list of GameObject pointers that can be rendered together
 *   using instanced rendering.
 *
 * This structure allows the renderer to:
 * - Group objects by layer
 * - Further batch objects by identical render resources
 * - Minimize draw calls during rendering
 */
using InstancedBatchMap = std::unordered_map<int, std::unordered_map<InstanceBatchKey, std::vector<GameObject*>>>;
